name: doxygen

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create storage directory for math
      shell: bash
      run: mkdir math
      
    - name: Grab website repo
      uses: actions/checkout@v4
      with:
        repository: ttaute/ttaute.github.io

    - name: Delete old documentation
      shell: bash
      run: rm -r doc
      
    - name: Grab math repo
      uses: actions/checkout@v4
      with:
        repository: ttaute/math
        path: './math'

    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'math/Doxyfile'

    - name: Create artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./doc/html

    - name: Git status
      shell: bash
      run: git status

    - name: Delete math since it is not needed anymore
      shell: bash
      run: rm -r math

    - name: Git Configure
      shell: bash
      run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"

    - name: Git Add changes
      shell: bash
      run: git add --all

    - name: Git create commit
      shell: bash
      run: git commit -m "update"

    - name: Git Push
      shell: bash
      run: git push

    - name: push documentation
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main' # your branch name goes here
