name: doxygen

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Grab repo
      uses: actions/checkout@v4
    
    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1

    - name: Create artifacts
      uses: actions/upload-artifact@v4
      with:
        path: doc/math

    - name: Upload documentation to website
      uses: EndBug/add-and-commit@v9
      with:
        add: 'doc'
        default_author: github_actions
