name: doxygen

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create storage directory for math
      shell: bash
      run: mkdir math
      
    - name: Grab website repo
      uses: actions/checkout@v4
      with:
        repository: ttaute/ttaute.github.io

    - name: Delete old documentation
      shell: bash
      run: rm -r doc
      
    - name: Grab math repo
      uses: actions/checkout@v4
      with:
        repository: ttaute/math
        path: './math'

    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'math/Doxyfile'

    - name: Create artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ./doc/html

    - name: Delete math repo from worker
      shell: bash
      run: rm -r math

    - name: Push documentation to website
      id: pushdoc
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT_PUSH }}
      with:
        destination-github-username: 'ttaute'
        destination-repository-name: 'ttaute.github.io'
        commit-message: Pushing documentation generated from math
